main: me.branbran.lcmaps.LCMaps
name: LCMaps
version: 1.0

description: Contains the guis for linkcraft maps!

commands:
  menu:
    description: Open the linkcraft maps menu.
    permission: lcmaps.menu
    